name: whats_sender
description: A Dart package for sending WhatsApp messages and managing OTP (One-Time Password) functionality via the Softeks WhatsApp API.
version: 1.0.0
repository: https://github.com/MoamenRabee/whatsapp_sender

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
